services:
  - type: web
    name: meo-ranking-server
    env: node
    buildCommand: bash render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
